train: /home/wei/Radar_Object_Detector/data/whole_train/images
val: /home/wei/Radar_Object_Detector/data/whole_train/images
test: /home/wei/Radar_Object_Detector/data/testing_data/city_7_0/images

nc: 1
names: ["car"]